// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {pb} from '../models';

export function Add(arg1:pb.BCRequest):Promise<pb.BCResponse>;

export function Greet(arg1:string):Promise<string>;
