// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: basic_calculation.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BasicCalculationClient is the client API for BasicCalculation service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BasicCalculationClient interface {
	Add(ctx context.Context, in *BCRequest, opts ...grpc.CallOption) (*BCResponse, error)
}

type basicCalculationClient struct {
	cc grpc.ClientConnInterface
}

func NewBasicCalculationClient(cc grpc.ClientConnInterface) BasicCalculationClient {
	return &basicCalculationClient{cc}
}

func (c *basicCalculationClient) Add(ctx context.Context, in *BCRequest, opts ...grpc.CallOption) (*BCResponse, error) {
	out := new(BCResponse)
	err := c.cc.Invoke(ctx, "/basic_calculation.BasicCalculation/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BasicCalculationServer is the server API for BasicCalculation service.
// All implementations must embed UnimplementedBasicCalculationServer
// for forward compatibility
type BasicCalculationServer interface {
	Add(context.Context, *BCRequest) (*BCResponse, error)
	mustEmbedUnimplementedBasicCalculationServer()
}

// UnimplementedBasicCalculationServer must be embedded to have forward compatible implementations.
type UnimplementedBasicCalculationServer struct {
}

func (UnimplementedBasicCalculationServer) Add(context.Context, *BCRequest) (*BCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedBasicCalculationServer) mustEmbedUnimplementedBasicCalculationServer() {}

// UnsafeBasicCalculationServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BasicCalculationServer will
// result in compilation errors.
type UnsafeBasicCalculationServer interface {
	mustEmbedUnimplementedBasicCalculationServer()
}

func RegisterBasicCalculationServer(s grpc.ServiceRegistrar, srv BasicCalculationServer) {
	s.RegisterService(&BasicCalculation_ServiceDesc, srv)
}

func _BasicCalculation_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BasicCalculationServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/basic_calculation.BasicCalculation/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BasicCalculationServer).Add(ctx, req.(*BCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BasicCalculation_ServiceDesc is the grpc.ServiceDesc for BasicCalculation service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BasicCalculation_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "basic_calculation.BasicCalculation",
	HandlerType: (*BasicCalculationServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _BasicCalculation_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "basic_calculation.proto",
}
