// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: simple_statistics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SimpleStatisticsDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Row    string    `protobuf:"bytes,1,opt,name=row,proto3" json:"row,omitempty"`
	Values []float32 `protobuf:"fixed32,2,rep,packed,name=values,proto3" json:"values,omitempty"`
}

func (x *SimpleStatisticsDataType) Reset() {
	*x = SimpleStatisticsDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_statistics_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleStatisticsDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleStatisticsDataType) ProtoMessage() {}

func (x *SimpleStatisticsDataType) ProtoReflect() protoreflect.Message {
	mi := &file_simple_statistics_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleStatisticsDataType.ProtoReflect.Descriptor instead.
func (*SimpleStatisticsDataType) Descriptor() ([]byte, []int) {
	return file_simple_statistics_proto_rawDescGZIP(), []int{0}
}

func (x *SimpleStatisticsDataType) GetRow() string {
	if x != nil {
		return x.Row
	}
	return ""
}

func (x *SimpleStatisticsDataType) GetValues() []float32 {
	if x != nil {
		return x.Values
	}
	return nil
}

type SimpleStatisticsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data    *SimpleStatisticsDataType `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Methods []string                  `protobuf:"bytes,2,rep,name=methods,proto3" json:"methods,omitempty"`
}

func (x *SimpleStatisticsRequest) Reset() {
	*x = SimpleStatisticsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_statistics_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleStatisticsRequest) ProtoMessage() {}

func (x *SimpleStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_statistics_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleStatisticsRequest.ProtoReflect.Descriptor instead.
func (*SimpleStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_simple_statistics_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleStatisticsRequest) GetData() *SimpleStatisticsDataType {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SimpleStatisticsRequest) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type SimpleStatisticsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Steps  string `protobuf:"bytes,1,opt,name=steps,proto3" json:"steps,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *SimpleStatisticsResponse) Reset() {
	*x = SimpleStatisticsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_statistics_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleStatisticsResponse) ProtoMessage() {}

func (x *SimpleStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simple_statistics_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleStatisticsResponse.ProtoReflect.Descriptor instead.
func (*SimpleStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_simple_statistics_proto_rawDescGZIP(), []int{2}
}

func (x *SimpleStatisticsResponse) GetSteps() string {
	if x != nil {
		return x.Steps
	}
	return ""
}

func (x *SimpleStatisticsResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_simple_statistics_proto protoreflect.FileDescriptor

var file_simple_statistics_proto_rawDesc = []byte{
	0x0a, 0x17, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x11, 0x73, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x22, 0x44, 0x0a, 0x18,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x6f, 0x77, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x6f, 0x77, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x02, 0x52, 0x06, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x22, 0x74, 0x0a, 0x17, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x3f, 0x0a,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2b, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73,
	0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x73, 0x22, 0x48, 0x0a, 0x18, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x65, 0x70, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x32, 0x87, 0x01, 0x0a, 0x18, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x41, 0x6e, 0x61, 0x6c, 0x79, 0x73, 0x69, 0x73, 0x12,
	0x6b, 0x0a, 0x10, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x12, 0x2a, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74,
	0x61, 0x74, 0x69, 0x73, 0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2b, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x73, 0x74,
	0x69, 0x63, 0x73, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x73,
	0x74, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x11, 0x5a, 0x0f,
	0x2e, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simple_statistics_proto_rawDescOnce sync.Once
	file_simple_statistics_proto_rawDescData = file_simple_statistics_proto_rawDesc
)

func file_simple_statistics_proto_rawDescGZIP() []byte {
	file_simple_statistics_proto_rawDescOnce.Do(func() {
		file_simple_statistics_proto_rawDescData = protoimpl.X.CompressGZIP(file_simple_statistics_proto_rawDescData)
	})
	return file_simple_statistics_proto_rawDescData
}

var file_simple_statistics_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_simple_statistics_proto_goTypes = []interface{}{
	(*SimpleStatisticsDataType)(nil), // 0: simple_statistics.SimpleStatisticsDataType
	(*SimpleStatisticsRequest)(nil),  // 1: simple_statistics.SimpleStatisticsRequest
	(*SimpleStatisticsResponse)(nil), // 2: simple_statistics.SimpleStatisticsResponse
}
var file_simple_statistics_proto_depIdxs = []int32{
	0, // 0: simple_statistics.SimpleStatisticsRequest.data:type_name -> simple_statistics.SimpleStatisticsDataType
	1, // 1: simple_statistics.SimpleStatisticsAnalysis.SimpleStatistics:input_type -> simple_statistics.SimpleStatisticsRequest
	2, // 2: simple_statistics.SimpleStatisticsAnalysis.SimpleStatistics:output_type -> simple_statistics.SimpleStatisticsResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_simple_statistics_proto_init() }
func file_simple_statistics_proto_init() {
	if File_simple_statistics_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simple_statistics_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleStatisticsDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_statistics_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleStatisticsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_statistics_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleStatisticsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simple_statistics_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simple_statistics_proto_goTypes,
		DependencyIndexes: file_simple_statistics_proto_depIdxs,
		MessageInfos:      file_simple_statistics_proto_msgTypes,
	}.Build()
	File_simple_statistics_proto = out.File
	file_simple_statistics_proto_rawDesc = nil
	file_simple_statistics_proto_goTypes = nil
	file_simple_statistics_proto_depIdxs = nil
}
