// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.1
// source: simple_statistics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SimpleStatisticsAnalysisClient is the client API for SimpleStatisticsAnalysis service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SimpleStatisticsAnalysisClient interface {
	SimpleStatistics(ctx context.Context, in *SimpleStatisticsRequest, opts ...grpc.CallOption) (*SimpleStatisticsResponse, error)
}

type simpleStatisticsAnalysisClient struct {
	cc grpc.ClientConnInterface
}

func NewSimpleStatisticsAnalysisClient(cc grpc.ClientConnInterface) SimpleStatisticsAnalysisClient {
	return &simpleStatisticsAnalysisClient{cc}
}

func (c *simpleStatisticsAnalysisClient) SimpleStatistics(ctx context.Context, in *SimpleStatisticsRequest, opts ...grpc.CallOption) (*SimpleStatisticsResponse, error) {
	out := new(SimpleStatisticsResponse)
	err := c.cc.Invoke(ctx, "/simple_statistics.SimpleStatisticsAnalysis/SimpleStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SimpleStatisticsAnalysisServer is the server API for SimpleStatisticsAnalysis service.
// All implementations must embed UnimplementedSimpleStatisticsAnalysisServer
// for forward compatibility
type SimpleStatisticsAnalysisServer interface {
	SimpleStatistics(context.Context, *SimpleStatisticsRequest) (*SimpleStatisticsResponse, error)
	mustEmbedUnimplementedSimpleStatisticsAnalysisServer()
}

// UnimplementedSimpleStatisticsAnalysisServer must be embedded to have forward compatible implementations.
type UnimplementedSimpleStatisticsAnalysisServer struct {
}

func (UnimplementedSimpleStatisticsAnalysisServer) SimpleStatistics(context.Context, *SimpleStatisticsRequest) (*SimpleStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimpleStatistics not implemented")
}
func (UnimplementedSimpleStatisticsAnalysisServer) mustEmbedUnimplementedSimpleStatisticsAnalysisServer() {
}

// UnsafeSimpleStatisticsAnalysisServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SimpleStatisticsAnalysisServer will
// result in compilation errors.
type UnsafeSimpleStatisticsAnalysisServer interface {
	mustEmbedUnimplementedSimpleStatisticsAnalysisServer()
}

func RegisterSimpleStatisticsAnalysisServer(s grpc.ServiceRegistrar, srv SimpleStatisticsAnalysisServer) {
	s.RegisterService(&SimpleStatisticsAnalysis_ServiceDesc, srv)
}

func _SimpleStatisticsAnalysis_SimpleStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimpleStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SimpleStatisticsAnalysisServer).SimpleStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/simple_statistics.SimpleStatisticsAnalysis/SimpleStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SimpleStatisticsAnalysisServer).SimpleStatistics(ctx, req.(*SimpleStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SimpleStatisticsAnalysis_ServiceDesc is the grpc.ServiceDesc for SimpleStatisticsAnalysis service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SimpleStatisticsAnalysis_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "simple_statistics.SimpleStatisticsAnalysis",
	HandlerType: (*SimpleStatisticsAnalysisServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SimpleStatistics",
			Handler:    _SimpleStatisticsAnalysis_SimpleStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "simple_statistics.proto",
}
