// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: statistics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StatisticsServiceClient is the client API for StatisticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StatisticsServiceClient interface {
	AnalyzeDescriptiveStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsDescriptiveResponse, error)
	AnalyzeInferentialStatistics(ctx context.Context, in *InferentialStatisticsRequest, opts ...grpc.CallOption) (*AnyhowResponse, error)
	AnalyzeTimeSeriesStatistics(ctx context.Context, in *TimeSeriesAnalysisRequest, opts ...grpc.CallOption) (*AnyhowResponse, error)
}

type statisticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStatisticsServiceClient(cc grpc.ClientConnInterface) StatisticsServiceClient {
	return &statisticsServiceClient{cc}
}

func (c *statisticsServiceClient) AnalyzeDescriptiveStatistics(ctx context.Context, in *StatisticsRequest, opts ...grpc.CallOption) (*StatisticsDescriptiveResponse, error) {
	out := new(StatisticsDescriptiveResponse)
	err := c.cc.Invoke(ctx, "/statistics.StatisticsService/AnalyzeDescriptiveStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) AnalyzeInferentialStatistics(ctx context.Context, in *InferentialStatisticsRequest, opts ...grpc.CallOption) (*AnyhowResponse, error) {
	out := new(AnyhowResponse)
	err := c.cc.Invoke(ctx, "/statistics.StatisticsService/AnalyzeInferentialStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *statisticsServiceClient) AnalyzeTimeSeriesStatistics(ctx context.Context, in *TimeSeriesAnalysisRequest, opts ...grpc.CallOption) (*AnyhowResponse, error) {
	out := new(AnyhowResponse)
	err := c.cc.Invoke(ctx, "/statistics.StatisticsService/AnalyzeTimeSeriesStatistics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StatisticsServiceServer is the server API for StatisticsService service.
// All implementations must embed UnimplementedStatisticsServiceServer
// for forward compatibility
type StatisticsServiceServer interface {
	AnalyzeDescriptiveStatistics(context.Context, *StatisticsRequest) (*StatisticsDescriptiveResponse, error)
	AnalyzeInferentialStatistics(context.Context, *InferentialStatisticsRequest) (*AnyhowResponse, error)
	AnalyzeTimeSeriesStatistics(context.Context, *TimeSeriesAnalysisRequest) (*AnyhowResponse, error)
	mustEmbedUnimplementedStatisticsServiceServer()
}

// UnimplementedStatisticsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStatisticsServiceServer struct {
}

func (UnimplementedStatisticsServiceServer) AnalyzeDescriptiveStatistics(context.Context, *StatisticsRequest) (*StatisticsDescriptiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeDescriptiveStatistics not implemented")
}
func (UnimplementedStatisticsServiceServer) AnalyzeInferentialStatistics(context.Context, *InferentialStatisticsRequest) (*AnyhowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeInferentialStatistics not implemented")
}
func (UnimplementedStatisticsServiceServer) AnalyzeTimeSeriesStatistics(context.Context, *TimeSeriesAnalysisRequest) (*AnyhowResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AnalyzeTimeSeriesStatistics not implemented")
}
func (UnimplementedStatisticsServiceServer) mustEmbedUnimplementedStatisticsServiceServer() {}

// UnsafeStatisticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StatisticsServiceServer will
// result in compilation errors.
type UnsafeStatisticsServiceServer interface {
	mustEmbedUnimplementedStatisticsServiceServer()
}

func RegisterStatisticsServiceServer(s grpc.ServiceRegistrar, srv StatisticsServiceServer) {
	s.RegisterService(&StatisticsService_ServiceDesc, srv)
}

func _StatisticsService_AnalyzeDescriptiveStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).AnalyzeDescriptiveStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.StatisticsService/AnalyzeDescriptiveStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).AnalyzeDescriptiveStatistics(ctx, req.(*StatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_AnalyzeInferentialStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InferentialStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).AnalyzeInferentialStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.StatisticsService/AnalyzeInferentialStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).AnalyzeInferentialStatistics(ctx, req.(*InferentialStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StatisticsService_AnalyzeTimeSeriesStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TimeSeriesAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StatisticsServiceServer).AnalyzeTimeSeriesStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/statistics.StatisticsService/AnalyzeTimeSeriesStatistics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StatisticsServiceServer).AnalyzeTimeSeriesStatistics(ctx, req.(*TimeSeriesAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StatisticsService_ServiceDesc is the grpc.ServiceDesc for StatisticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StatisticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "statistics.StatisticsService",
	HandlerType: (*StatisticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeDescriptiveStatistics",
			Handler:    _StatisticsService_AnalyzeDescriptiveStatistics_Handler,
		},
		{
			MethodName: "AnalyzeInferentialStatistics",
			Handler:    _StatisticsService_AnalyzeInferentialStatistics_Handler,
		},
		{
			MethodName: "AnalyzeTimeSeriesStatistics",
			Handler:    _StatisticsService_AnalyzeTimeSeriesStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "statistics.proto",
}
