# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: simple_statistics.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17simple_statistics.proto\x12\x11simple_statistics\"7\n\x18SimpleStatisticsDataType\x12\x0b\n\x03row\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\"e\n\x17SimpleStatisticsRequest\x12\x39\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32+.simple_statistics.SimpleStatisticsDataType\x12\x0f\n\x07methods\x18\x02 \x03(\t\"9\n\x18SimpleStatisticsResponse\x12\r\n\x05steps\x18\x01 \x01(\t\x12\x0e\n\x06result\x18\x02 \x01(\t2\x87\x01\n\x18SimpleStatisticsAnalysis\x12k\n\x10SimpleStatistics\x12*.simple_statistics.SimpleStatisticsRequest\x1a+.simple_statistics.SimpleStatisticsResponseB\x11Z\x0f./server/proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'simple_statistics_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./server/proto/'
  _globals['_SIMPLESTATISTICSDATATYPE']._serialized_start=46
  _globals['_SIMPLESTATISTICSDATATYPE']._serialized_end=101
  _globals['_SIMPLESTATISTICSREQUEST']._serialized_start=103
  _globals['_SIMPLESTATISTICSREQUEST']._serialized_end=204
  _globals['_SIMPLESTATISTICSRESPONSE']._serialized_start=206
  _globals['_SIMPLESTATISTICSRESPONSE']._serialized_end=263
  _globals['_SIMPLESTATISTICSANALYSIS']._serialized_start=266
  _globals['_SIMPLESTATISTICSANALYSIS']._serialized_end=401
# @@protoc_insertion_point(module_scope)
