# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.simple_statistics_pb2 as simple__statistics__pb2


class SimpleStatisticsAnalysisStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SimpleStatistics = channel.unary_unary(
                '/simple_statistics.SimpleStatisticsAnalysis/SimpleStatistics',
                request_serializer=simple__statistics__pb2.SimpleStatisticsRequest.SerializeToString,
                response_deserializer=simple__statistics__pb2.SimpleStatisticsResponse.FromString,
                )


class SimpleStatisticsAnalysisServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SimpleStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SimpleStatisticsAnalysisServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SimpleStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.SimpleStatistics,
                    request_deserializer=simple__statistics__pb2.SimpleStatisticsRequest.FromString,
                    response_serializer=simple__statistics__pb2.SimpleStatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simple_statistics.SimpleStatisticsAnalysis', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SimpleStatisticsAnalysis(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SimpleStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/simple_statistics.SimpleStatisticsAnalysis/SimpleStatistics',
            simple__statistics__pb2.SimpleStatisticsRequest.SerializeToString,
            simple__statistics__pb2.SimpleStatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
