# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pb.statistics_pb2 as statistics__pb2


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeSimpleStatistics = channel.unary_unary(
                '/statistics.StatisticsService/AnalyzeSimpleStatistics',
                request_serializer=statistics__pb2.StatisticsRequest.SerializeToString,
                response_deserializer=statistics__pb2.StatisticsResponse.FromString,
                )
        self.AnalyzeAdvancedStatistics = channel.unary_unary(
                '/statistics.StatisticsService/AnalyzeAdvancedStatistics',
                request_serializer=statistics__pb2.StatisticsRequest.SerializeToString,
                response_deserializer=statistics__pb2.StatisticsResponse.FromString,
                )


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeSimpleStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeAdvancedStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeSimpleStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeSimpleStatistics,
                    request_deserializer=statistics__pb2.StatisticsRequest.FromString,
                    response_serializer=statistics__pb2.StatisticsResponse.SerializeToString,
            ),
            'AnalyzeAdvancedStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeAdvancedStatistics,
                    request_deserializer=statistics__pb2.StatisticsRequest.FromString,
                    response_serializer=statistics__pb2.StatisticsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeSimpleStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics.StatisticsService/AnalyzeSimpleStatistics',
            statistics__pb2.StatisticsRequest.SerializeToString,
            statistics__pb2.StatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeAdvancedStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/statistics.StatisticsService/AnalyzeAdvancedStatistics',
            statistics__pb2.StatisticsRequest.SerializeToString,
            statistics__pb2.StatisticsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
