# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: statistics.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10statistics.proto\x12\nstatistics\x1a\x1cgoogle/protobuf/struct.proto\"1\n\x12StatisticsDataType\x12\x0b\n\x03row\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x02\"R\n\x11StatisticsRequest\x12,\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1e.statistics.StatisticsDataType\x12\x0f\n\x07methods\x18\x02 \x03(\t\"/\n\x1dStatisticsDescriptiveResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"H\n\x1dStatisticsInferentialResponse\x12\'\n\x06result\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct2\xe7\x01\n\x11StatisticsService\x12h\n\x1c\x41nalyzeDescriptiveStatistics\x12\x1d.statistics.StatisticsRequest\x1a).statistics.StatisticsDescriptiveResponse\x12h\n\x1c\x41nalyzeInferentialStatistics\x12\x1d.statistics.StatisticsRequest\x1a).statistics.StatisticsInferentialResponseB\x11Z\x0f./server/proto/b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'statistics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\017./server/proto/'
  _globals['_STATISTICSDATATYPE']._serialized_start=62
  _globals['_STATISTICSDATATYPE']._serialized_end=111
  _globals['_STATISTICSREQUEST']._serialized_start=113
  _globals['_STATISTICSREQUEST']._serialized_end=195
  _globals['_STATISTICSDESCRIPTIVERESPONSE']._serialized_start=197
  _globals['_STATISTICSDESCRIPTIVERESPONSE']._serialized_end=244
  _globals['_STATISTICSINFERENTIALRESPONSE']._serialized_start=246
  _globals['_STATISTICSINFERENTIALRESPONSE']._serialized_end=318
  _globals['_STATISTICSSERVICE']._serialized_start=321
  _globals['_STATISTICSSERVICE']._serialized_end=552
# @@protoc_insertion_point(module_scope)
