# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pb.statistics_pb2 as statistics__pb2

GRPC_GENERATED_VERSION = '1.64.1'
GRPC_VERSION = grpc.__version__
EXPECTED_ERROR_RELEASE = '1.65.0'
SCHEDULED_RELEASE_DATE = 'June 25, 2024'
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    warnings.warn(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in statistics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
        + f' This warning will become an error in {EXPECTED_ERROR_RELEASE},'
        + f' scheduled for release on {SCHEDULED_RELEASE_DATE}.',
        RuntimeWarning
    )


class StatisticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AnalyzeDescriptiveStatistics = channel.unary_unary(
                '/statistics.StatisticsService/AnalyzeDescriptiveStatistics',
                request_serializer=statistics__pb2.StatisticsRequest.SerializeToString,
                response_deserializer=statistics__pb2.StatisticsDescriptiveResponse.FromString,
                _registered_method=True)
        self.AnalyzeInferentialStatistics = channel.unary_unary(
                '/statistics.StatisticsService/AnalyzeInferentialStatistics',
                request_serializer=statistics__pb2.InferentialStatisticsRequest.SerializeToString,
                response_deserializer=statistics__pb2.AnyhowResponse.FromString,
                _registered_method=True)
        self.AnalyzeTimeSeriesStatistics = channel.unary_unary(
                '/statistics.StatisticsService/AnalyzeTimeSeriesStatistics',
                request_serializer=statistics__pb2.TimeSeriesAnalysisRequest.SerializeToString,
                response_deserializer=statistics__pb2.AnyhowResponse.FromString,
                _registered_method=True)


class StatisticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AnalyzeDescriptiveStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeInferentialStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeTimeSeriesStatistics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StatisticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AnalyzeDescriptiveStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeDescriptiveStatistics,
                    request_deserializer=statistics__pb2.StatisticsRequest.FromString,
                    response_serializer=statistics__pb2.StatisticsDescriptiveResponse.SerializeToString,
            ),
            'AnalyzeInferentialStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeInferentialStatistics,
                    request_deserializer=statistics__pb2.InferentialStatisticsRequest.FromString,
                    response_serializer=statistics__pb2.AnyhowResponse.SerializeToString,
            ),
            'AnalyzeTimeSeriesStatistics': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeTimeSeriesStatistics,
                    request_deserializer=statistics__pb2.TimeSeriesAnalysisRequest.FromString,
                    response_serializer=statistics__pb2.AnyhowResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'statistics.StatisticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('statistics.StatisticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StatisticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AnalyzeDescriptiveStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/AnalyzeDescriptiveStatistics',
            statistics__pb2.StatisticsRequest.SerializeToString,
            statistics__pb2.StatisticsDescriptiveResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeInferentialStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/AnalyzeInferentialStatistics',
            statistics__pb2.InferentialStatisticsRequest.SerializeToString,
            statistics__pb2.AnyhowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AnalyzeTimeSeriesStatistics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/statistics.StatisticsService/AnalyzeTimeSeriesStatistics',
            statistics__pb2.TimeSeriesAnalysisRequest.SerializeToString,
            statistics__pb2.AnyhowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
