name: Deploy Microservices

on:
  push:
    branches:
      - main
    paths:
      - "server/**"
      - "analysis_server/**"
jobs:
  build_microservices:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Dockerized Microservices (GO Server & Analysis Server)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ixios/
            git fetch
            git pull
            docker compose down
            docker image rm ixios-server ixios-analysis_server
            docker compose up -d
